name: social_ice
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.5
  google_nav_bar: ^5.0.6
  lottie: ^3.0.0
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.4
  image_picker: ^1.0.7
  firebase_storage: ^11.6.5
  video_player: ^2.8.2
  video_thumbnail: ^0.5.3
  cached_network_image: ^3.3.1
  preload_page_view: ^0.2.0
  visibility_detector: ^0.4.0+2
  string_validator: ^1.0.2
  expandable_text: ^2.3.0
  contained_tab_bar_view: ^0.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
flutter:

  
  uses-material-design: true
  assets:
    - assets/
    - assets/logos/
    - assets/lottie/
    - assets/images/

  